version: '3.9'
services:
  backend:
    build: 
      context: /home/adeel/backend-dice
      dockerfile: Dockerfile
    init: true
    networks:
    - application
  frontend:
    build: 
      context: /home/adeel/frontend-dice/
      dockerfile: Dockerfile
    init: true
    environment:
      BACKEND_URL: backend:8080
    networks:
    - application
    ports:
    - "9091:8080"
    depends_on:
    - backend
  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: adeel@123
      MYSQL_DATABASE: dice

volumes:
  mysql-data:
networks:
  application:
    name: application
